// app/constants/constantdata.js
const roleWordPairs = [
 { spyWord: "Pani Puri", villagerWord: "Chaat" },
  { spyWord: "Biryani", villagerWord: "Pulao" },
  { spyWord: "Dosa", villagerWord: "Idli" },
  { spyWord: "Butter Chicken", villagerWord: "Paneer" },
  { spyWord: "Samosa", villagerWord: "Pakora" },
  { spyWord: "Lassi", villagerWord: "Buttermilk" },
  { spyWord: "Rasgulla", villagerWord: "Gulab Jamun" },
  { spyWord: "Roti", villagerWord: "Naan" },
  { spyWord: "Chole", villagerWord: "Rajma" },
  { spyWord: "Tandoori", villagerWord: "Grill" },
  { spyWord: "Mumbai", villagerWord: "Delhi" },
  { spyWord: "Goa", villagerWord: "Kerala" },
  { spyWord: "Agra", villagerWord: "Jaipur" },
  { spyWord: "Varanasi", villagerWord: "Haridwar" },
  { spyWord: "Manali", villagerWord: "Shimla" },
  { spyWord: "Amritsar", villagerWord: "Ludhiana" },
  { spyWord: "Pune", villagerWord: "Nagpur" },
  { spyWord: "Hyderabad", villagerWord: "Chennai" },
  { spyWord: "Bangalore", villagerWord: "Mysore" },
  { spyWord: "Udaipur", villagerWord: "Jodhpur" },

  { spyWord: "Diwali", villagerWord: "Holi" },
  { spyWord: "Eid", villagerWord: "Ramzan" },
  { spyWord: "Pongal", villagerWord: "Onam" },
  { spyWord: "Navratri", villagerWord: "Durga Puja" },
  { spyWord: "Ganesh Chaturthi", villagerWord: "Janmashtami" },
  { spyWord: "Baisakhi", villagerWord: "Lohri" },
  { spyWord: "Karwa Chauth", villagerWord: "Teej" },
  { spyWord: "Raksha Bandhan", villagerWord: "Bhai Dooj" },
  { spyWord: "Christmas", villagerWord: "Good Friday" },
  { spyWord: "Mahashivratri", villagerWord: "Shravan" },

  // Mythology
  { spyWord: "Krishna", villagerWord: "Rama" },
  { spyWord: "Hanuman", villagerWord: "Shiva" },
  { spyWord: "Lakshmi", villagerWord: "Saraswati" },
  { spyWord: "Arjuna", villagerWord: "Karna" },
  { spyWord: "Duryodhana", villagerWord: "Bhima" },
  { spyWord: "Ganesha", villagerWord: "Murugan" },
  { spyWord: "Vishnu", villagerWord: "Shiva" },
  { spyWord: "Sita", villagerWord: "Draupadi" },
  { spyWord: "Indra", villagerWord: "Agni" },
  { spyWord: "Ravana", villagerWord: "Kumbhakarna" },

  // Bollywood
  { spyWord: "SRK", villagerWord: "Salman" },
  { spyWord: "Karan Johar", villagerWord: "Sanjay Leela" },
  { spyWord: "DDLJ", villagerWord: "Kabir Singh" },
  { spyWord: "Bahubali", villagerWord: "KGF" },
  { spyWord: "Ranbir", villagerWord: "Ranveer" },
  { spyWord: "Katrina", villagerWord: "Deepika" },
  { spyWord: "Aamir", villagerWord: "Hrithik" },
  { spyWord: "Sholay", villagerWord: "Deewar" },
  { spyWord: "Bigg Boss", villagerWord: "Roadies" },
  { spyWord: "Dharma", villagerWord: "YRF" },

  // spyWord Culture
  { spyWord: "Rickshaw", villagerWord: "Taxi" },
  { spyWord: "Kurta", villagerWord: "Sherwani" },
  { spyWord: "Saree", villagerWord: "Lehenga" },
  { spyWord: "Namaste", villagerWord: "Pranam" },
  { spyWord: "Laddu", villagerWord: "Barfi" },
  { spyWord: "Chapati", villagerWord: "Paratha" },
  { spyWord: "Cricket", villagerWord: "Kabaddi" },
  { spyWord: "Yoga", villagerWord: "Meditation" },
  { spyWord: "Jugaad", villagerWord: "Hack" },
  { spyWord: "Desi", villagerWord: "Videshi" },

  // Clothing & Accessories
  { spyWord: "Bindi", villagerWord: "Sindoor" },
  { spyWord: "Jutti", villagerWord: "Chappal" },
  { spyWord: "Pagdi", villagerWord: "Topi" },
  { spyWord: "Dupatta", villagerWord: "Stole" },
  { spyWord: "Mundu", villagerWord: "Dhoti" },
  { spyWord: "Choli", villagerWord: "Blouse" },
  { spyWord: "Anarkali", villagerWord: "Salwar" },
  { spyWord: "Tika", villagerWord: "Mangalsutra" },
  { spyWord: "Payal", villagerWord: "Bangle" },
  { spyWord: "Mehendi", villagerWord: "Haldi" },

  // Education & Careers
  { spyWord: "IIT", villagerWord: "NIT" },
  { spyWord: "NEET", villagerWord: "JEE" },
  { spyWord: "UPSC", villagerWord: "SSC" },
  { spyWord: "MBA", villagerWord: "BBA" },
  { spyWord: "Engineering", villagerWord: "Doctor" },
  { spyWord: "IAS", villagerWord: "IPS" },
  { spyWord: "Teacher", villagerWord: "Professor" },
  { spyWord: "Lawyer", villagerWord: "Judge" },
  { spyWord: "CA", villagerWord: "Accountant" },
  { spyWord: "Coder", villagerWord: "Developer" },

  // Indian Brands
  { spyWord: "Amul", villagerWord: "Mother Dairy" },
  { spyWord: "Tata", villagerWord: "Reliance" },
  { spyWord: "Air India", villagerWord: "IndiGo" },
  { spyWord: "Zomato", villagerWord: "Swiggy" },
  { spyWord: "Ola", villagerWord: "Uber" },
  { spyWord: "Big Bazaar", villagerWord: "D-Mart" },
  { spyWord: "Airtel", villagerWord: "Jio" },
  { spyWord: "Flipkart", villagerWord: "Amazon" },
  { spyWord: "MakeMyTrip", villagerWord: "Yatra" },
  { spyWord: "Paytm", villagerWord: "PhonePe" },
   { spyWord: "kumbh", villagerWord: "yatra" },
  { spyWord: "rangoli", villagerWord: "alpana" },
  { spyWord: "dandiya", villagerWord: "bhangra" },
  { spyWord: "dhoti", villagerWord: "lungi" },
  { spyWord: "thepla", villagerWord: "paratha" },
  { spyWord: "kachori", villagerWord: "puri" },
  { spyWord: "modak", villagerWord: "laddu" },
  { spyWord: "bharatanatyam", villagerWord: "kathak" },
  { spyWord: "thali", villagerWord: "platter" },
  { spyWord: "pagdi", villagerWord: "topi" },
  { spyWord: "kundli", villagerWord: "panchang" },
  { spyWord: "tulsi", villagerWord: "neem" },
  { spyWord: "panchayat", villagerWord: "sabha" },
  { spyWord: "palki", villagerWord: "rath" },
  { spyWord: "kolam", villagerWord: "rangoli" },
  { spyWord: "lota", villagerWord: "kalash" },
  { spyWord: "haldi", villagerWord: "chandan" },
  { spyWord: "bindi", villagerWord: "sindoor" },
  { spyWord: "shiksha", villagerWord: "vidya" },
  { spyWord: "rasgulla", villagerWord: "chamcham" },
  { spyWord: "betel", villagerWord: "areca" },
  { spyWord: "charpai", villagerWord: "manji" },
  { spyWord: "dal", villagerWord: "sambar" },
  { spyWord: "holika", villagerWord: "rakshabandhan" },
  { spyWord: "agni", villagerWord: "dhoop" },
  { spyWord: "mehndi", villagerWord: "alta" },
  { spyWord: "tilak", villagerWord: "tika" },
  { spyWord: "vada", villagerWord: "bhajiya" },
  { spyWord: "upma", villagerWord: "poha" },
  { spyWord: "kanjeevaram", villagerWord: "banarasi" },
  { spyWord: "murti", villagerWord: "idol" },
  { spyWord: "akshar", villagerWord: "varna" },
  { spyWord: "mridangam", villagerWord: "nadaswaram" },
  { spyWord: "rajma", villagerWord: "chole" },
  { spyWord: "pakhala", villagerWord: "khichdi" },
  { spyWord: "dhol", villagerWord: "nagada" },
  { spyWord: "charkha", villagerWord: "loom" },
  { spyWord: "bazaar", villagerWord: "haat" },
  { spyWord: "ghee", villagerWord: "oil" },
  { spyWord: "chillum", villagerWord: "hookah" },
  { spyWord: "aarti", villagerWord: "bhajan" },
  { spyWord: "tandoor", villagerWord: "sigdi" },
  { spyWord: "jharokha", villagerWord: "verandah" },
  { spyWord: "kund", villagerWord: "ghat" },
  { spyWord: "lathi", villagerWord: "talwar" },
  { spyWord: "matha", villagerWord: "mandir" },
  { spyWord: "gilli", villagerWord: "danda" },
  { spyWord: "maalish", villagerWord: "ubtan" },
  { spyWord: "prasad", villagerWord: "bhog" },
  { spyWord: "nimbu", villagerWord: "amla" },
  { spyWord: "satvik", villagerWord: "rajasic" },
  { spyWord: "peepal", villagerWord: "banyan" },
  { spyWord: "dahi", villagerWord: "lassi" },
  { spyWord: "pithla", villagerWord: "bhakri" },
  { spyWord: "sindoor", villagerWord: "kumkum" },
  { spyWord: "parikrama", villagerWord: "pradakshina" },
  { spyWord: "nataraj", villagerWord: "shivling" },
  { spyWord: "abhishek", villagerWord: "archana" },
  { spyWord: "sehra", villagerWord: "dupatta" },
  { spyWord: "tulwar", villagerWord: "kirpan" },
  { spyWord: "dhunuchi", villagerWord: "aarti" },
  { spyWord: "lagan", villagerWord: "shaadi" },
  { spyWord: "jhula", villagerWord: "palna" },
  { spyWord: "bansuri", villagerWord: "shehnai" },
  { spyWord: "sitar", villagerWord: "tanpura" },
  { spyWord: "gajak", villagerWord: "rewri" },
  { spyWord: "havan", villagerWord: "yagya" },
  { spyWord: "kurkure", villagerWord: "namkeen" },
  { spyWord: "khichri", villagerWord: "pongal" },
  { spyWord: "ghunghat", villagerWord: "veil" },
  { spyWord: "phirni", villagerWord: "kheer" },
  { spyWord: "lotus", villagerWord: "plumeria" },
  { spyWord: "shankh", villagerWord: "bell" },
  { spyWord: "matka", villagerWord: "ghada" },
  { spyWord: "gulal", villagerWord: "abir" },
  { spyWord: "kachha", villagerWord: "langot" },
  { spyWord: "halwai", villagerWord: "mithaiwala" },
  { spyWord: "sitaron", villagerWord: "taare" },
  { spyWord: "mantra", villagerWord: "shloka" },
  { spyWord: "bazaar", villagerWord: "mandi" },
  { spyWord: "chappar", villagerWord: "chhat" },
  { spyWord: "phulkari", villagerWord: "kantha" },
  { spyWord: "navratri", villagerWord: "durga puja" },
  { spyWord: "diyas", villagerWord: "candles" },
  { spyWord: "biryani", villagerWord: "tahari" },
  { spyWord: "peda", villagerWord: "barfi" },
  { spyWord: "sherwani", villagerWord: "kurta" },
  { spyWord: "golgappa", villagerWord: "batasha" },
  { spyWord: "dupatta", villagerWord: "odhni" },
  { spyWord: "achaar", villagerWord: "murabba" },
  { spyWord: "feni", villagerWord: "toddy" },
  { spyWord: "kachha", villagerWord: "lungi" },
  { spyWord: "kulfi", villagerWord: "icecream" },
  { spyWord: "nadaswaram", villagerWord: "shehnai" },
  { spyWord: "mithai", villagerWord: "dessert" },
  { spyWord: "satyanarayan", villagerWord: "shivratri" },
  { spyWord: "tilgul", villagerWord: "gur" },
  { spyWord: "jaapi", villagerWord: "topi" },
  { spyWord: "ghaghra", villagerWord: "lehenga" },
  { spyWord: "maidan", villagerWord: "akhara" },
  { spyWord: "desi", villagerWord: "videshi" }
];

export default roleWordPairs;
